module.exports =  {
"": "Inter",
"": "Epilogue",
"": "DM Serif Text",
"hero": "DM Serif Text",
"subtitle": "Inter",
"label": "Inter",
"body-1": "Inter",
"body-2": "Inter",
"h5": "DM Serif Text",
"h4": "DM Serif Text",
"h3": "DM Serif Text",
"h2": "DM Serif Text",
"h1": "DM Serif Text",
"button-label": "Inter",
"button-label-small": "Inter",
"link-1": "Inter",
"link-2": "Inter",
}