name: Process Figma Tokens PR

on: pull_request

jobs:
  run_if: # only if base branch is "figma-tokens"
    if: ${{ github.head_ref == 'figma-tokens' }}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # checkout to the head of this PR
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: yarn install

      - name: Run token-transformer
        run: npx token-transformer tokens/donnie.json tokens/figma-tokens-output.json  --resolveReferences false

      - name: Transform tokens
        run: npx token-transformer src/theme/token-transformation/raw-tokens.json src/theme/token-transformation/global.json global  --resolveReferences --expandTypography=true
      - name: Transform tokens
        run: npx token-transformer src/theme/token-transformation/raw-tokens.json src/theme/token-transformation/light.json light  --resolveReferences
      - name: Transform tokens
        run: npx token-transformer src/theme/token-transformation/raw-tokens.json src/theme/token-transformation/typography.json typography  --resolveReferences --expandTypography=true

      - name: Build css using Style Dictionary
        run: node src/theme/scripts/build-style-dictionary.js

      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Commit files
        run: git config --local user.email "pelicansinberlin@gmail.com"
          git config --local user.name "daniel kalman"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
